name: cities_of_the_world
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  
  # External packages
  flutter_bloc: ^8.1.6
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0

  # Internal packages
  core:
    path: ./packages/core
  domain:
    path: ./packages/domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
