name: domain
description: "Domain layer of the project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Internal packages
  core:
    path: ../core
  data:
    path: ../data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true