name: Mobile build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build-android:
    name: Build Android test force push
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Intall java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17.x'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: dart analyze
      
      - name: Build apk
        run: flutter build apk
      - name: Run tests
        run: flutter test

  build-ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Intall java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17.x'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: "stable"

      - name: Install packages dependencies
        run: ./build_cities_of_the_world.sh

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze
      
      - name: Build IPA
        run: flutter build ipa --no-codesign
        
      - name: Run tests
        run: flutter test
